apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-python
spec:
  serviceName: {{ include "app-python.fullname" . }}-headless
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: atkond/flask-app:latest
          ports:
            - containerPort: 5000 
